### ISSUE TITLE
Release 0.6.11-rc

### ISSUE THREAD

**Issue by pabelnl** [pokt-network/pocket-js-LEGACY#388]
The next release includes:

- [x] issue #386 -Query Nodes Should Not Fill in the Defaults

- [x] issue #380 -Handle Code 14 Relay with Optional Dispatch Field

- [x] issue #379 - Block / Account Tx Query Does Not Parse Msg and StdTx

- [x] issue #387 - Improve relay error

- [X] issue #389 - Add new RPC QueryUpgrade

**Comment by pabelnl** [comment]
completed with PRs #388 and Issue #389
